### ISSUE TITLE
support for new uniprot website?

### ISSUE THREAD

**Issue by czanetti** [gingraslab/remove-signal-peptides#1]
Hello, 

I tried following the steps but I think uniprot changed in the meantime and it doesn't appear to work with the current instructions.
It's not clear to me, does the tsv file need to be containing only signal sequences? 

thanks

**Comment by knightjdr** [comment]
It looks like there is a new URL format. I've updated the readme so see if that works for you now. The tsv file should have seven columns, with the signal peptides in the 7th column.

**Comment by czanetti** [comment]
Thank you, it works now! Great tool

I would suggest to include the information regarding the 7th column in the readme.md
I use a uniprot layout that resulted in signal information to be exported on the 8th.

cheers

**Comment by knightjdr** [comment]
Glad it worked. And I've updated the readme now too based on your suggestion.
